### ISSUE TITLE
64-bit Support

### ISSUE THREAD

**Issue by kentcb** [xunit/xamarin.xunit#6]
Need to switch to the unified API in order to support 64-bit.

**Comment by onovotny** [comment]
This is in progress. Just hit a snag with Xamarin changing a path name on the device for 64-bit so it might be a bit....we'll see.

**Comment by onovotny** [comment]
This is now supported in RC1: https://www.nuget.org/packages/xunit.runner.xamarin/

**Comment by kentcb** [comment]
Thanks @onovotny. I noticed the package has a dependency on xunit >= 2.0.0rc1-build2826. However, per [this issue](https://github.com/xunit/xunit/issues/279), I haven't been able to install that version of xunit due to Xamarin Studio having too old a version of NuGet.

Am I missing something?
